### ISSUE TITLE
 In makefile syntax, the cd command is valid only on the current line.

### ISSUE THREAD

**Issue by aka-polyhedron** [koddr/example-go-react-macos-app-1#1]
```
cd ui
npm install
npm run build
```
the above code should be this
```
cd ui && npm install && npm run build
```

**Comment by koddr** [comment]
@sun63270325 hi!

Both your and my solution, are similar ways to write `Makefile`, but I stay on my point, because it's more clear to understand (for beginners). 

P.S. and it's not `Dockerfile`, where each line is a new layer and we want to save it.

**Comment by indiependente** [comment]
Hi @koddr , 

nice work here!
I have to agree with @sun63270325, `make build` fails (on macOS at least) because of the reason highlighted. 
`npm` is not able to find the `package.json` file, since the `npm install` is not executed in the `ui` folder.

The following build target works for me:
```Makefile
build: clean
	@cd ui && \
	npm install && \
	npm run build && \
	cd .. && \
	mkdir -p ./helloworld.app/Contents/MacOS && \
	go build -o ./helloworld.app/Contents/MacOS/helloworld && \
	echo "[✔️] Build complete!"
```

**Comment by koddr** [comment]
Hmmm... 🤔 

As I tested below, current Makefile works fine on macOS (I'm working on MBP):

```makefile
build: clean
	@cd ./ui && npm install
	@cd ./ui && npm run build
	@mkdir -p ./helloworld.app/Contents/MacOS
	@go build -o ./helloworld.app/Contents/MacOS/helloworld
	@echo "[✔️] Build complete!"
```

Maybe you're running `make build` out of root folder or something else?

EDIT: I tested again on macOS and Ubuntu, current version of Makefile is okay and works.
