### ISSUE TITLE
What parameters need to be changed in the source code of the Full HD application?

### ISSUE THREAD

**Issue by elvis-hp** [koddr/example-go-react-macos-app-1#17]
Can you guys can help me?

**Comment by koddr** [comment]
Hi! 

What's actually mean `the Full HD application`?

**Comment by elvis-hp** [comment]
that's  right @koddr.

**Comment by koddr** [comment]
Try to set right sizes here:

```go
	// Let's open window app with:
	//  - name: Golang App
	//  - address: http://localhost:8000
	//  - sizes: 800x600 px
	//  - resizable: true
	webview.Open("Golang App", "http://localhost:5000", 800, 600, true)
```

**Comment by elvis-hp** [comment]
Hi, I have tried 
webview.Open("App", "http://localhost:8000", 4024, 768, true)
it show full screen, but it's still blurred. 

![image](https://user-images.githubusercontent.com/4811620/90143704-213b4c80-dda8-11ea-95c8-835c84c9fc5d.png)

![image](https://user-images.githubusercontent.com/4811620/90143825-4465fc00-dda8-11ea-8855-b257a094a9bb.png)

**Comment by koddr** [comment]
Oh, I understand. 

Which OS do you compiled for? I know issue on Windows systems with blur effect, because `webview` package use the default browser in your system for view content. For Windows 10 it's Edge or Internet Explorer 11.

**Comment by elvis-hp** [comment]
I'm using Macbook.
![image](https://user-images.githubusercontent.com/4811620/90152854-7a0fe280-ddb2-11ea-8343-87731477078d.png)

**Comment by elvis-hp** [comment]
If I run: "go run main.go" => it's OK.
but run: "make" or "open helloworld.app", it's blurred. I don't know why!

**Comment by elvis-hp** [comment]
if I cd to: Contents/MacOS and run: ./helloworld => it's blurred
if I rename MacOS => MacOSabc and run: ./helloworld => it's ok.
I think that related to the system OS.

**Comment by elvis-hp** [comment]
I found solution. thanks!

**Comment by koddr** [comment]
Hmm... strange, but OK, if it works :+1:
